# MongoDB Connection parameters
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://JananiSivasankar:Janani2407@cluster0.rqcvycq.mongodb.net/ecommerceDB?retryWrites=true&w=majority&appName=Cluster0}

# MySQL Database


# Ollama settings
ollama.base-url=${OLLAMA_URL:http://host.docker.internal:11434}
ollama.model=${OLLAMA_MODEL:phi3:mini}
ollama.embed-model=${OLLAMA_EMBED_MODEL:nomic-embed-text}

logging.level.com.example.orderservice=DEBUG
